pdf : presentation clean

presentation : 
	pdflatex presentation.tex
	pdflatex presentation.tex
	pdflatex presentation.tex

clean : 
	rm -f *.aux 
	rm -f *.nav 
	rm -f *.log 
	rm -f *.out 
	rm -f *.snm 
	rm -f *.toc
	rm -f *.auxlock
